name: Workflow
on: workflow_dispatch
jobs:
 basic:
  runs-on: ubuntu latest
  steps:
   - name: print greeting
     run: |
         echo"good morning"
         echo"this is my second workflow"
   - name: print good bye
     run: |
         echo "gud night"
         echo "bye"
